=== pandas-dev/pandas/venv/lib/python3.12/site-packages/jsonschema_specifications/schemas/draft3/metaschema.json
{
	"$schema" : "http://json-schema.org/draft-03/schema#",
	"id" : "http://json-schema.org/draft-03/schema#",
	"type" : "object",

	"properties" : {
		"type" : {
			"type" : ["string", "array"],
			"items" : {
				"type" : ["string", {"$ref" : "#"}]
			},
			"uniqueItems" : true,
			"default" : "any"
		},

		"properties" : {
			"type" : "object",
			"additionalProperties" : {"$ref" : "#"},
			"default" : {}
		},

		"patternProperties" : {
			"type" : "object",
			"additionalProperties" : {"$ref" : "#"},
			"default" : {}
		},

		"additionalProperties" : {
			"type" : [{"$ref" : "#"}, "boolean"],
			"default" : {}
		},

		"items" : {
			"type" : [{"$ref" : "#"}, "array"],
			"items" : {"$ref" : "#"},
			"default" : {}
		},

		"additionalItems" : {
			"type" : [{"$ref" : "#"}, "boolean"],
			"default" : {}
		},

		"required" : {
			"type" : "boolean",
			"default" : false
		},

		"dependencies" : {
			"type" : "object",
			"additionalProperties" : {
				"type" : ["string", "array", {"$ref" : "#"}],
				"items" : {
					"type" : "string"
				}
			},
			"default" : {}
		},

		"minimum" : {
			"type" : "number"
		},

		"maximum" : {
			"type" : "number"
		},

		"exclusiveMinimum" : {
			"type" : "boolean",
			"default" : false
		},

		"exclusiveMaximum" : {
			"type" : "boolean",
			"default" : false
		},

		"minItems" : {
			"type" : "integer",
			"minimum" : 0,
			"default" : 0
		},

		"maxItems" : {
			"type" : "integer",
			"minimum" : 0
		},

		"uniqueItems" : {
			"type" : "boolean",
			"default" : false
		},

		"pattern" : {
			"type" : "string",
			"format" : "regex"
		},

		"minLength" : {
			"type" : "integer",
			"minimum" : 0,
			"default" : 0
		},

		"maxLength" : {
			"type" : "integer"
		},

		"enum" : {
			"type" : "array",
			"minItems" : 1,
			"uniqueItems" : true
		},

		"default" : {
			"type" : "any"
		},

		"title" : {
			"type" : "string"
		},

		"description" : {
			"type" : "string"
		},

		"format" : {
			"type" : "string"
		},

		"divisibleBy" : {
			"type" : "number",
			"minimum" : 0,
			"exclusiveMinimum" : true,
			"default" : 1
		},

		"disallow" : {
			"type" : ["string", "array"],
			"items" : {
				"type" : ["string", {"$ref" : "#"}]
			},
			"uniqueItems" : true
		},

		"extends" : {
			"type" : [{"$ref" : "#"}, "array"],
			"items" : {"$ref" : "#"},
			"default" : {}
		},

		"id" : {
			"type" : "string"
		},

		"$ref" : {
			"type" : "string"
		},

		"$schema" : {
			"type" : "string",
			"format" : "uri"
		}
	},

	"dependencies" : {
		"exclusiveMinimum" : "minimum",
		"exclusiveMaximum" : "maximum"
	},

	"default" : {}
}

=== pandas-dev/pandas/venv/lib/python3.12/site-packages/jupyterlab/schemas/@jupyterlab/apputils-extension/sessionDialogs.json
{
  "title": "Kernel dialogs",
  "description": "Kernel dialogs settings.",
  "additionalProperties": false,
  "properties": {
    "skipKernelRestartDialog": {
      "title": "Skip kernel restart Dialog",
      "description": "Whether the kernel restart confirmation dialog is skipped when restarting the kernel.",
      "type": "boolean",
      "default": false
    }
  },
  "type": "object"
}

=== pandas-dev/pandas/venv/share/jupyter/labextensions/@jupyter-widgets/jupyterlab-manager/schemas/@jupyter-widgets/jupyterlab-manager/plugin.json
{
  "title": "Jupyter Widgets",
  "description": "Jupyter widgets settings.",
  "additionalProperties": false,
  "properties": {
    "saveState": {
      "type": "boolean",
      "title": "Save Jupyter widget state in notebooks",
      "description": "Automatically save Jupyter widget state when a notebook is saved.",
      "default": false
    }
  },
  "type": "object"
}

=== pandas-dev/pandas/venv/share/jupyter/lab/schemas/@jupyterlab/settingeditor-extension/form-ui.json
{
  "title": "Settings Editor Form UI",
  "description": "Settings editor form ui settings.",
  "properties": {
    "settingEditorType": {
      "title": "Type of editor for the setting.",
      "description": "Set the type of editor to use while editing your settings.",
      "enum": ["json", "ui"],
      "default": "ui"
    }
  },
  "additionalProperties": false,
  "type": "object"
}

=== pandas-dev/pandas/venv/lib/python3.12/site-packages/jupyterlab_server/test_data/schemas/@jupyterlab/apputils-extension/themes.json
{
  "title": "Theme",
  "description": "Theme manager settings.",
  "properties": {
    "theme": {
      "type": "string",
      "title": "Selected Theme",
      "default": "JupyterLab Light"
    },
    "codeCellConfig": {
      "title": "Code Cell Configuration",
      "description": "The configuration for all code cells.",
      "$ref": "#/definitions/editorConfig",
      "default": {
        "autoClosingBrackets": true,
        "cursorBlinkRate": 530,
        "fontFamily": null,
        "fontSize": null,
        "lineHeight": null,
        "lineNumbers": false,
        "lineWrap": "off",
        "matchBrackets": true,
        "readOnly": false,
        "insertSpaces": true,
        "tabSize": 4,
        "wordWrapColumn": 80,
        "rulers": [],
        "codeFolding": false,
        "lineWiseCopyCut": true
      }
    }
  },
  "type": "object"
}

=== pandas-dev/pandas/venv/lib/python3.12/site-packages/jupyter_lsp/specs/config/julia-language-server.schema.json
{
  "title": "Julia Language Server Configuration",
  "description": "Extracted from https://github.com/julia-vscode/julia-vscode/blob/master/package.json; markdownDescription â†’ description; removed Code-specific options, retained the overlap with https://github.com/julia-vscode/LanguageServer.jl/blob/36d8da744c1cb517cca3ba19180ddd276c1c6bf5/src/requests/workspace.jl#L88-L103; distributed under MIT License Copyright (c) 2012-2019 David Anthoff, Zac Nugent and other contributors (https://github.com/JuliaLang/Julia.tmbundle/contributors, https://github.com/julia-vscode/julia-vscode/contributors)",
  "type": "object",
  "properties": {
    "julia.lint.run": {
      "type": "boolean",
      "default": true,
      "description": "Run the linter on active files."
    },
    "julia.lint.missingrefs": {
      "type": "string",
      "default": "none",
      "enum": ["none", "symbols", "all"],
      "description": "Highlight unknown symbols. The `symbols` option will not mark unknown fields."
    },
    "julia.lint.disabledDirs": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": ["docs", "test"],
      "description": "Specifies sub-directories in [a package directory](https://docs.julialang.org/en/v1/manual/code-loading/#Package-directories-1) where only basic linting is. This drastically lowers the chance for false positives."
    },
    "julia.lint.call": {
      "type": "boolean",
      "default": true,
      "description": "This compares  call signatures against all known methods for the called function. Calls with too many or too few arguments, or unknown keyword parameters are highlighted."
    },
    "julia.lint.iter": {
      "type": "boolean",
      "default": true,
      "description": "Check iterator syntax of loops. Will identify, for example, attempts to iterate over single values."
    },
    "julia.lint.nothingcomp": {
      "type": "boolean",
      "default": true,
      "description": "Check for use of `==` rather than `===` when comparing against `nothing`. "
    },
    "julia.lint.constif": {
      "type": "boolean",
      "default": true,
      "description": "Check for constant conditionals in if statements that result in branches never being reached.."
    },
    "julia.lint.lazy": {
      "type": "boolean",
      "default": true,
      "description": "Check for deterministic lazy boolean operators."
    },
    "julia.lint.datadecl": {
      "type": "boolean",
      "default": true,
      "description": "Check variables used in type declarations are datatypes."
    },
    "julia.lint.typeparam": {
      "type": "boolean",
      "default": true,
      "description": "Check parameters declared in `where` statements or datatype declarations are used."
    },
    "julia.lint.modname": {
      "type": "boolean",
      "default": true,
      "description": "Check submodule names do not shadow their parent's name."
    },
    "julia.lint.pirates": {
      "type": "boolean",
      "default": true,
      "description": "Check for type piracy - the overloading of external functions with methods specified for external datatypes. 'External' here refers to imported code."
    },
    "julia.lint.useoffuncargs": {
      "type": "boolean",
      "default": true,
      "description": "Check that all declared arguments are used within the function body."
    },
    "julia.completionmode": {
      "type": "string",
      "default": "qualify",
      "description": "Sets the mode for completions.",
      "enum": ["exportedonly", "import", "qualify"],
      "enumDescriptions": [
        "Show completions for the current namespace.",
        "Show completions for the current namespace and unexported variables of `using`ed modules. Selection of an unexported variable will result in the automatic insertion of an explicit `using` statement.",
        "Show completions for the current namespace and unexported variables of `using`ed modules. Selection of an unexported variable will complete to a qualified variable name."
      ],
      "scope": "window"
    }
  }
}

=== pandas-dev/pandas/venv/lib/python3.12/site-packages/jupyter_lsp/specs/config/typescript-language-server.schema.json
{
  "title": "TypeScript Language Server Configuration",
  "description": "Based on https://github.com/typescript-language-server/typescript-language-server; TODO: add formatting preferences once formatting is supported.",
  "type": "object",
  "properties": {
    "diagnostics.ignoredCodes": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "default": [],
      "description": "Diagnostics code to be omitted when reporting diagnostics. See https://github.com/microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json for a full list of valid codes."
    },
    "completions.completeFunctionCalls": {
      "type": "boolean",
      "default": false,
      "description": "Complete functions with their parameter signature."
    }
  }
}
